### ISSUE TITLE
todo: post v2.0 release

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#254]
## code refactoring
- [ ] `get_mob_stats` 
    - [ ] output needs to be in as a `tibble` or `data.frame` for each pushing to `ggplot` per #242
    - [ ] make sure row ids or site ids are properly implemented in output per #199 
    - [ ] turn off randomization tests by default because often inappropriate
    - [ ] make it work for just a community matrix input with a grouping vector rather than only on a `mob_in` object (see similar behavior in `rarefaction`)
    - [ ] issue warning if unbalanced design. 
    - [ ] if coordinates are provided then do a quick extent check on each grouping factor see if they are similar issue warning if not
- [ ] `make_mob_in`
    - [ ] allow input data to be in long or wide format for community matrix, key assumption will be that attribute data is provided in similar way - this makes things a little tricky. 
    - [ ] make sure it is clear that presence absence data is not currently supported 
    - [ ] needs to accept just a vector for the `plot_attr` argument rather than a full `data.frame` see #41
- [ ] `rarefaction`
    - [ ] make individual based per site easier per #209 
    - [ ] `dens_ratio` argument is difficult to understand per #238 
    - [ ] consider dropping `lchoose` for `lgamma` throughout so that floating point abundances can be used per #207 this applies to case in which sampling effort is rounded (need better implementation of rejected PR #184)
    - [ ] when plotting there are currently limited colors implemented should patch per #222
- [ ] `get_delta_stats
    - [ ] report proportional change in richness rather than only absolute per #165 

## new functionality
- [ ] add in @T-Engel 's beta diversity statistics from https://github.com/T-Engel/betaC
- [ ] calc_SPIE needed to provide a means of computing S_PIE when site has all singletons (i.e., PIE = 1 which results in a division by zero and therefore an NA value. Essentially this is the difference between using asymptotic S or observed S. Note this replaces some of the functionality of the `calc_PIE` function
- [ ] spatially explicit sSBR that expresses S as a function of distance rather than number of samples collected
- [ ] extending MoB to binary presence / absence data - which represents a change from SAD to OFD and density to fill of matrix per #89 
- [ ] change `get_mob_stats` and `get_delta_stats` over to a formula specification per #239 
- [ ] more complex experimental designs need to be implemented (e.g., block designs per #129).
- [ ] consider depreciating some function names in favor of new names (e.g., `get_mob_stats` and `get_delta_stats` are not a great names consider multimetric and multiscale or something similar that matches terminology in papers)

**Comment by dmcglinn** [comment]
tagging @T-Engel, @jmchase, and @sablowes here as this reflects our meeting on 2020/10/09

**Comment by T-Engel** [comment]
I changed calc_PIE in my fork. Will write a pull request once I've added the betas. 48224b3ac62ee83ff0791209f9032f0ee593303d

**Comment by dmcglinn** [comment]
Thanks @T-Engel! I'll commit on your fork at your commit

**Comment by T-Engel** [comment]
I just created a new branch from dev for the incorporation of beta_C. (Here: 040a9bb). Now we don't depend on the betaC package. Before we merge into dev, I want to update calc_com_div(). I don't think it makes sense for beta_C to show up as the default for index=S. Can we remove it from there? Maybe it is not a bad idea to leave beta_C out of this big function. If users want to use it, they can just call beta_C directly. Otherwise, calc_comm_div needs a C_target argument, as well. Otherwise, the coverage changes every time depending on the data.

**Comment by dmcglinn** [comment]
Hey @jmchase @sablowes @T-Engel @FelixMay it would be good to revisit this `mobr` wishlist. There still seems to be some important items that would be great if we develop a plan of implementation. Also a reprioritized list would likely be really helpful. Something to think about after mobr v3.0.0 comes out here in the next few weeks.

**Comment by FelixMay** [comment]
Hi  @dmcglinn, thanks for pushing this Dan. I am teaching for the next to weeks, but I am happy to talk or comment afterwards

**Comment by dmcglinn** [comment]
Sounds good thanks @FelixMay. I hope teaching goes well.
